### PR TITLE
Linting, Part 2

### PR DESCRIPTION
**Pull request by AlexAxthelm**
More progress on #40. Unless, I've misunderstood, this should wrap up what can be done without merge conflicts before 4.1.0?

I've tried to be consistent with the changes that I made in #72, including keeping each function's lints as its own commits, to make `git-blame` a bit easier.

All checks pass on my local machine, but I expect coverage to drop, like last time.

### CODE REVIEW

**Comment by wlandau-lilly** [comment]
Thank you, @AlexAxthelm! Retrospective linting can be tedious, and it really helps me out.

Can we wait on this one a little while? Version 4.1.0 is actually about to roll out. It just went through a time-consuming code review, all I need now is a senior director from IT to check a box.

**Comment by wlandau-lilly** [comment]
I confirmed that this PR can merge without conflicts. But again, I would prefer to push 4.1.0 first, and I also have a couple more requests.

- Would you also lint with development `lintr`? I generally prefer to use the CRAN versions of packages, but at the moment, dev `lintr` is not as forgiving.
- After 4.1.0 is out, would you be willing to boost the code coverage back up? It may seem silly to reach for 100%, but those uncovered lines handle the exact sort of boundary conditions that require special checking.

**Comment by AlexAxthelm** [comment]
Absolutely. I'll put dev `lintr` on now, and then go back and make any changes that I need to for this PR.

I'll try to bring coverage back up, but may need some help determining what the `expected` edge cases are.

**Comment by AlexAxthelm** [comment]
This will definitely need some more work, now that I'm using the dev version of `lintr`. It seems that it also runs lints on the `roxygen` comments, which `1.0.0` did not.

I have a strong suspicion that I will have to go back and relint the `roxygen` comments that I ignored in #79.

**Comment by wlandau-lilly** [comment]
Yup, no conflicts after I pushed 4.1.0!

**Comment by AlexAxthelm** [comment]
Awesome! I'll take care of roxygen next week, and let you know when this is ready to pull.

Just to be clear, I should be able to go ahead and lint all the other files that you listed in #40 as being in the queue for after 4.1.0?

**Comment by wlandau-lilly** [comment]
Everything is up for grabs for linting now. I will gladly wait for you.

**Comment by AlexAxthelm** [comment]
I think I've buttoned up the `R/` directory. I'm currently working on the `basic.R` example, then I'll start on tests.

My plan for tests is to do a literal linting of what is currently there, and then go back through and supplement until coverage is back up to 100%.

**Comment by wlandau-lilly** [comment]
Looks that way to me. Definitely much improved.

```r
                                        style warning error
inst/examples/basic/basic.R                54       0     0
tests/testthat/test-command-changes.R      13       0     0
tests/testthat/test-envir.R                26       0     0
tests/testthat/test-full-build.R           16       0     0
tests/testthat/test-generate.R             76       0     0
tests/testthat/test-import-object.R        18       0     0
tests/testthat/test-intermediate-file.R     7       0     0
tests/testthat/test-Makefile.R             35       0     0
tests/testthat/test-namespaced.R           17       0     0
```

If you rerun `roxygen2` again, this may actually be a good time for an intermediate merge. Yes, code coverage will decrease for a little bit, but other people will be able work on PRs more easily in the meantime.

**Comment by AlexAxthelm** [comment]
I ran `devtools::document()`, and made a commit. I had done one of the testfiles before I pushed, so that's in there too. 

I'm a bit nervous about touching them (which is why I'm doing it last), so if you could give them a second set of eyes, just to make sure that I don't drop any arguments or parens or such, I would appreciate it greatly.

**Comment by wlandau-lilly** [comment]
All my checks came out totally clear:

- [win-builder](https://win-builder.r-project.org), all 3 R versions
- `basic.R`, Windows 7, R-devel
- `basic.R`, Red Hat Linux, R 3.4.0
- `basic.R` with HPC enabled, Red Hat Linux, R 3.4.0
- `tests/extra/multiple.R`, Windows 7, R-devel
- `tests/extra/multiple.R`, Red Had Linux, R 3.4.0

I will merge your work so far to allow others to develop `R/*.R` without merge conflicts.

**Pull request merged**
